id: A8EDE99AE
title: Praise of Kunga Yeshe, Great Being and Master of Extensive Scriptural Traditions
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:20:45.071313
  last_modified_at: 2022-02-28 23:20:45.071329
